### Complementing a strand of DNA ###

def ReverseComplement(string):
    basepair = {'A': 'T', 'C': 'G', 'G': 'C', 'T': 'A'}
    rc_string = ''
    for base in string:
        rc_string += basepair[base]
    return rc_string[::-1]

sample_string = 'AAAACCCGGT'
test_string = 'GTGTGCGGCGAACTGTAATTATATTCTAGAATCGTTCCCATTAGACAAAGCCGTGAGTTCTACGACGGTTTGTGTTGCCTAGCGAGATCCCCGTTTCATAAGCGCGATCCGGCGCCTACAGGCATGGGCATACAGACTAGCGTAAGGATAGGTTTTCCTCGCACTGAATGCGGCCTCGGGCGATAAAGAGGCAATCGCCAGGTGTAGTCGCGCGGCGGCAGAACAATGTGATTGGCGGAGCGCAGCCGAACCACCCAGTTCTTGTTTCATGAAGGCCTGCGTGTAAGGTGACTAGGAAGGACGTAATTCTATGGCCCGGACGCCTGAATGCAGCATACACGCTCGGTTTGATTAATCGCTCCGGGACGAAGCCATTATGGGGGAATATGTGGTAAACGCGCAAACATGTCGGTTGGGGCCCGAAGATTTCACACTCCCCGCATCGCTTCTACCCCGTTCCGACAGCTGTCGTCAGCAGTCCGAAGGGAACCGACAGGTCCCCTAAGAATTTTTAGGCTGTTAGGAAATTCTTGAATTTATTGCATTTGAGAGTCATGAATGCTAATAAAACAAACCTCAGACTAAAGTAGCACATTGATCTCGTCTGAAGTATTCCTACTAGATTTGAAACTCTTCTTTAGTTTATGGGATTGACGTCTGGAATATAAGAACTGCAGAAATCATGAAGCTAGAACGGGCCTATCCAAGTGTAAGCATAAAATACAGTAAAGCCTTAGGATATAGCTCAAACCGGGTGCAGCTTAGTAACGAATTCTGCGGATTGGACGGTTTCTGAGACGACGTTATACAGTGCGATCTTACGAGC'
print(ReverseComplement(test_string))