### Finding a motif in DNA ###

def PatternOccurrence(pattern,genome):
    index = 0
    indexList = []
    for i in range(len(genome)-len(pattern)+1):
        if genome[i:i+len(pattern)] == pattern:
            indexList.append(index)
        index += 1
    return indexList

string = 'TATCGGGGTATAGCTAGAGTCTAGAGTACGACTAGAGTTGCTAGAGTCACTAGAGTCTAGAGTACTTGGTACAATGCTAGAGTCCTAGAGTCTAGAGTACCATGTTAACTAGAGTTCTAGAGTCTAGAGTCGCTAGAGTCTAGAGTCGCAAATTCTAGAGTCTAGAGTCCGTCCTAACTAGAGTGACTAGAGTGGGTGCTAGAGTGTTCTAGAGTCTAGAGTATCCTAGAGTCCCTAGAGTGGTACTAGAGTCTAGAGTAGAACTAGAGTTAACCGCGCCTAGAGTACCAGCTAGAGTCTAGAGTAGCTCTAGAGTCTAGAGTCGCGCCCTAGAGTACTAGAGTGCTGACTAGAGTATCCCTAGAGTCATCTAGAGTCTAGAGTCTAGAGTCTAGAGTTATGACGACTAGAGTGACTAGAGTTCTAGAGTCCTAGAGTACTAGAGTGCTAGAGTTGCGCTAGAGTCTAGAGTCTAGAGTTACTAGAGTCCTTTCTAGAGTACTGCTAGAGTCTAGAGTCTAGAGTCAGCTAGAGTCTAGAGTACTAGAGTGCTAGAGTATCTAGAGTGCTACGCTAGAGTTGTTGCTAGAGTTTCCTAGAGTCGCCTAGAGTACTCTAGAGTCTAGAGTCAGTCGCCTAGAGTCTAGAGTCTAGAGTCTAGAGTTCCTAGAGTCTAGAGTCTAGAGTGCTAGAGTCCACGGAGGGATACTAGAGTCCTAGAGTATTCTAGAGTGCGCTAGAGTGCTAGAGTCTAGAGTCTCTAGAGTCTAGAGTAGTTTTCTAGAGTGCTAGAGTGTGGCTAGAGTTCTAGTCTAGAGTCTAGAGTGCTAGAGTTCTAGAGTCCGCGTATTCCTAGAGTTAGGATTCTAGAGTGCTAGAGTCTAGAGTGACTAGAGT'
substring = 'CTAGAGTCT'
print(' '.join(str(int(idx)+1) for idx in PatternOccurrence(substring,string)))