### Finding genes with ORFs ###
from Bio.Seq import translate,Seq

string = 'TCTTAGAGGTAAGCATGGCAGAGCAGGACTCTTCGCCACTAGTTTAAGTTATGTTCGCGCTAATTGATCAACGAGGGGATCTGACTCCGGGCATAGGTCCTCGGGAGCACGAGATAGTGATTGAAGCGGGCTAATTATGTTAGGGAAAAAACGGTTCAAATATAGGCTGTAAATTAATTCTTAACTCGGCTTGAAAGTAATTTCGAAGGGGCATAGGGGGTTCAGGCGCTGGGTGAGCACAAGTTACCCTCACAAATAGTAACTTGACTTCATCTCAAGCACCTTGTGCTTGAGGTAAGGTCACGGTAACCACGAAATTAAAACACTCGACTACCTGACTACAGAGACCTGGGTCCGTTGTCAGGCAAGGTATTAGGCTGTAGGCCCTAGGGACGGAGTAAGTGTTTATTTTTGTAACGGAGTTTCTATCCCCCACAGAGGGCCACCATCTACAATCATGCTAACGATCTATGTGCACCATCCCGTATAGCTATACGGGATGGTGCACATAGATCGTTAGCATTAGCGCTAGACACTGCTCTCACCTGATGTATCAATATGGAGCTGGGCGCTTCTGAAGGGTGCGACATTCAAAGAGGACTAGAAAGTCTCGTTGAGGGTTGTCAGCAATAGTAGTGGTCGCAAATCCTAGCAGCTGGGCCCTACTCGCTAAGGGTGGCATCGTCGCTTTCTTGTGCCGAGCGGCGGCGTTACAGGAATCCGCGCAGCAGCGACTCGCTCGGCGTCAGGGCTCAGCTCCGTTGGCATAGAACTGTTTCCCAAGAAATCCTGTCACAATTAAGTGGCGTCGGTTCCCTTACGAGTATTCTTTGGAGTACTAGAGACCTTCCACGTGTAGACGCTAATATGCGGGATGGTACTTGCTTCCCCAGACCCGGAAATCTGAGTCGTTCCTGCAACAATCAGGTCTCTATGTCGTGCTAATAGATTTTGGTGCTACGAAATTCACTATGTACGGG'
strings = [string,str(Seq(string).reverse_complement())]

orfs = []
for seq in strings:
    for i in range(len(seq)-2):
        if seq[i:i+3] == 'ATG':
            substring = ''
            for j in range(i, len(seq)-2, 3):
                substring += seq[j:j+3]
                if seq[j:j+3] in ['TAA','TAG','TGA']:
                    break
            orfs.append(translate(substring,to_stop=True))
print(max(orfs,key=len))
