### Find the most frequent words in a string ###
from BA1A import PatternCount

def FrequentWords(text, k):
    frequentPatterns = set()
    count = []

    for i in range(len(text)-k+1):
        pattern = text[i:i+k]
        count.append(PatternCount(text,pattern))

    maxCount = max(count)
    for i in range(len(text)-k+1):
        if count[i] == maxCount:
            frequentPatterns.add(text[i:i+k])
    return frequentPatterns


text = 'GGTCTACTTAACACCATCGAAGATTGCGAAGATTGCGGTCTACTTGGTCTACTTCGTTCTACCCAGCTTAGGTCTACTTCCAGCTTACCAGCTTAAACACCATCAACACCATCAACACCATCGGTCTACTTAACACCATCGAAGATTGCCCAGCTTACCAGCTTAGGTCTACTTGGTCTACTTGAAGATTGCCGTTCTACCGTTCTACGGTCTACTTGGTCTACTTCGTTCTACCGTTCTACGAAGATTGCAACACCATCAACACCATCGAAGATTGCCGTTCTACCGTTCTACCCAGCTTAGAAGATTGCGAAGATTGCCCAGCTTAAACACCATCCGTTCTACCCAGCTTAAACACCATCCGTTCTACGGTCTACTTGAAGATTGCGGTCTACTTCCAGCTTACGTTCTACCGTTCTACAACACCATCGGTCTACTTAACACCATCAACACCATCCGTTCTACCCAGCTTAAACACCATCCGTTCTACGAAGATTGCCGTTCTACCGTTCTACCGTTCTACGGTCTACTTCGTTCTACCCAGCTTAGAAGATTGCAACACCATCGGTCTACTTGGTCTACTTGGTCTACTTCCAGCTTAAACACCATCCCAGCTTACCAGCTTACCAGCTTACGTTCTACCCAGCTTAGGTCTACTTGGTCTACTTAACACCATCCCAGCTTACGTTCTACCGTTCTACGGTCTACTTAACACCATCGGTCTACTTGAAGATTGCCCAGCTTACGTTCTACCGTTCTACAACACCATCCCAGCTTAGGTCTACTTGGTCTACTTCCAGCTTACGTTCTACCGTTCTACCGTTCTACCGTTCTACCGTTCTACGGTCTACTTAACACCATCGGTCTACTTGGTCTACTTGAAGATTGCGGTCTACTTCCAGCTTACGTTCTACCCAGCTTA'
k = 12
print(FrequentWords(text,k))