### Generate the k-mer composition of a string ###

def Composition(k,text):
    kmerList = []
    for i in range(len(text)-k+1):
        kmer = text[i:i+k]
        kmerList.append(kmer)

    return sorted(kmerList)

k = 50
string = 'GCCTTACATGTTGCTCACGCCCGGATACGATCGAGATCGTGTTTCCTAATAAAAATGAGGTTGATTGCTCCTCTGCGACTGATTGTGCATCTGAGCAGCGACGACAGGGGTAATACTATGAGTCATAAAAGTGCCCATGGATAAAGCTTATCTTAACATACAACGTTTTCAATCAAGCTTGCGAGTTTGCTTGGTCGCGCTGCTGCTTATTAGTTAAAACCGCTCATTCGGGTGTTCGGGTTCAGGGACTGCAGCATACTACTCGCACGGATGTCCGAGGGTCTGCCCCTGGGACATCCCTTCGCCACTCGTGCATGAAGCCAAGTTATGCGCCCAGCTGGACTCAGGTTTTGTAAAGCCATGGAATTTACAGCGCTAGGGTTGCTAGGGTGCTGCTTAGCTTACGTAGGAGTGGTATTCCCAAGTTACTCATAGCTGGCCTAGCAATCCCTTCCTCGCGGTGCGCGACAGCGGTTGTCATTCTATGCGTTGGACCACAGCGTGCGTTACGCGTTGGACTTTGGCTATGCAACTGGTTACCTCCCCCGGCCGTCTGTTCACATAAGACTTTTAGTCTCAGGGTGCGCAATTAGAGCAACTTGCCTCACCCAATTTAAGTTCTGGGCTGACACGAGTTATCACAGATCCTAATCAATCAGGATCCCGGGGGAAACGCACCAGTATTGCATCTTAATTTATAGGTGTAGCACCATCCTTCTCCTCTGGCTGAAGCGAGGCTGGTGTACCGCGGAAATGCACACGCCACCACGAACGGAGTTCATATGCAAAGAGGAGATTAACCAGCGGGGTGTGGAGTTTGAGCTCATGCGATGACCGAAGTGACGCTGGTGCTCCCGGACCTTTTAGGGGTCCGTTAGACTGGACACGCGTTTCATATGCACGGGTCGGTCTATGATTTAGACACCCAGGGCAAATGCATATCCGTACGCTGGGGCCTTACGCTAACCATCTGAAAAGTCCTGCCTACGTACCGTCAACC'
#print(Composition(k,string))

answer = ''
for kmer in Composition(k,string):
    answer += kmer + '\n'
answer = answer[:-1]
print(answer)